apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  labels:
    application: node-redis-example-5
    component: redis-server
    type: single
spec:
  replicas: 1
  selector:
    matchLabels:
      application: node-redis-example-5
      component: redis-server
      type: single
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: node-redis-example-5
        component: redis-server
        type: single
    spec:
      containers:
        - image: redis-server:1.0.0
          name: redis-server
          volumeMounts:
            - mountPath: /redis-data
              name: redis-data
          ports:
            - containerPort: 6379
              name: http
              protocol: TCP
      volumes:
        - name: redis-data
          hostPath:
            path: /run/desktop/mnt/host/c/redis-data
            type: DirectoryOrCreate