apiVersion: v1
kind: Service
metadata:
  name: redis-server
  labels:
    application: node-redis-example-5
    component: redis-server
    type: single
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    application: node-redis-example-5
    component: redis-server
    type: single